services:
  redis:
    image: redis:7-alpine
    container_name: ai-studio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    container_name: ai-studio-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Docker environment flag
      - DOCKER_ENV=1
      # Redis configuration
      - REDIS_URL=redis://redis:6379/0
      - JOB_STORAGE_BACKEND=redis
      # API Configuration
      - API_TITLE=AI-Studio API
      - API_VERSION=1.0.0
      - HOST=0.0.0.0
      - PORT=8000
      # Authentication (set JWT_SECRET_KEY in .env for production!)
      - REQUIRE_AUTH=true
      # - JWT_SECRET_KEY=your-secret-key-here  # Set this in .env!

    depends_on:
      redis:
        condition: service_healthy

    volumes:
      # Persistent volumes
      - ./presets:/app/presets           # Preset storage (persistent)
      - ./output:/app/output             # Generated images (persistent)
      - ./logs:/app/logs                 # Application logs (persistent)
      - ./data:/app/data                 # User accounts and persistent data

      # Optional volumes
      - ./cache:/app/cache               # Cache (can be ephemeral)
      - ./uploads:/app/uploads           # Temporary uploads
      - ./subjects:/app/subjects         # Subject images for composition

      # Mount configs (read-only)
      - ./configs:/app/configs:ro

      # Development volumes (for testing and live code updates)
      - ./api:/app/api                   # API source code
      - ./ai_tools:/app/ai_tools         # AI tools source code
      - ./tests:/app/tests               # Test files

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  frontend:
    build: ./frontend
    container_name: ai-studio-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped

# Optional: Add volumes for named volumes instead of bind mounts
volumes:
  redis_data:
    driver: local
  presets:
    driver: local
  output:
    driver: local
  cache:
    driver: local
