"""Initial database schema with all entities

Revision ID: f85c460c4214
Revises: 
Create Date: 2025-10-22 22:41:18.110384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85c460c4214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('board_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=True),
    sa.Column('designer', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('player_count_min', sa.Integer(), nullable=True),
    sa.Column('player_count_max', sa.Integer(), nullable=True),
    sa.Column('playtime_min', sa.Integer(), nullable=True),
    sa.Column('playtime_max', sa.Integer(), nullable=True),
    sa.Column('complexity', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_board_games_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_games'))
    )
    op.create_index(op.f('ix_board_games_bgg_id'), 'board_games', ['bgg_id'], unique=False)
    op.create_index(op.f('ix_board_games_game_id'), 'board_games', ['game_id'], unique=True)
    op.create_index(op.f('ix_board_games_name'), 'board_games', ['name'], unique=False)
    op.create_index(op.f('ix_board_games_user_id'), 'board_games', ['user_id'], unique=False)
    op.create_index('ix_boardgame_bgg_id', 'board_games', ['bgg_id'], unique=False)
    op.create_index('ix_boardgame_user_name', 'board_games', ['user_id', 'name'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('physical_description', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('reference_image_path', sa.String(length=500), nullable=True),
    sa.Column('age', sa.String(length=100), nullable=True),
    sa.Column('skin_tone', sa.String(length=100), nullable=True),
    sa.Column('face_description', sa.Text(), nullable=True),
    sa.Column('hair_description', sa.Text(), nullable=True),
    sa.Column('body_description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characters_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    op.create_index('ix_character_user_id_name', 'characters', ['user_id', 'name'], unique=False)
    op.create_index(op.f('ix_characters_character_id'), 'characters', ['character_id'], unique=True)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_table('clothing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('item', sa.String(length=500), nullable=False),
    sa.Column('fabric', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('source_image', sa.String(length=500), nullable=True),
    sa.Column('preview_image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clothing_items_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clothing_items'))
    )
    op.create_index(op.f('ix_clothing_items_category'), 'clothing_items', ['category'], unique=False)
    op.create_index(op.f('ix_clothing_items_item_id'), 'clothing_items', ['item_id'], unique=True)
    op.create_index(op.f('ix_clothing_items_user_id'), 'clothing_items', ['user_id'], unique=False)
    op.create_index('ix_clothing_user_category', 'clothing_items', ['user_id', 'category'], unique=False)
    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style_genre', sa.String(length=100), nullable=True),
    sa.Column('formality', sa.String(length=100), nullable=True),
    sa.Column('clothing_item_ids', sa.JSON(), nullable=False),
    sa.Column('source_image', sa.String(length=500), nullable=True),
    sa.Column('preview_image_path', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_outfits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outfits'))
    )
    op.create_index(op.f('ix_outfits_outfit_id'), 'outfits', ['outfit_id'], unique=True)
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('character_id', sa.String(length=50), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('story_type', sa.String(length=50), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], name=op.f('fk_stories_character_id_characters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_index(op.f('ix_stories_character_id'), 'stories', ['character_id'], unique=False)
    op.create_index(op.f('ix_stories_story_id'), 'stories', ['story_id'], unique=True)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.create_table('story_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.String(length=50), nullable=False),
    sa.Column('story_id', sa.String(length=50), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('illustration_prompt', sa.Text(), nullable=True),
    sa.Column('illustration_url', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.story_id'], name=op.f('fk_story_scenes_story_id_stories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_scenes'))
    )
    op.create_index('ix_scene_story_number', 'story_scenes', ['story_id', 'scene_number'], unique=False)
    op.create_index(op.f('ix_story_scenes_scene_id'), 'story_scenes', ['scene_id'], unique=True)
    op.create_index(op.f('ix_story_scenes_story_id'), 'story_scenes', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_scenes_story_id'), table_name='story_scenes')
    op.drop_index(op.f('ix_story_scenes_scene_id'), table_name='story_scenes')
    op.drop_index('ix_scene_story_number', table_name='story_scenes')
    op.drop_table('story_scenes')
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_story_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_character_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_outfits_user_id'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_outfit_id'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index('ix_clothing_user_category', table_name='clothing_items')
    op.drop_index(op.f('ix_clothing_items_user_id'), table_name='clothing_items')
    op.drop_index(op.f('ix_clothing_items_item_id'), table_name='clothing_items')
    op.drop_index(op.f('ix_clothing_items_category'), table_name='clothing_items')
    op.drop_table('clothing_items')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_character_id'), table_name='characters')
    op.drop_index('ix_character_user_id_name', table_name='characters')
    op.drop_table('characters')
    op.drop_index('ix_boardgame_user_name', table_name='board_games')
    op.drop_index('ix_boardgame_bgg_id', table_name='board_games')
    op.drop_index(op.f('ix_board_games_user_id'), table_name='board_games')
    op.drop_index(op.f('ix_board_games_name'), table_name='board_games')
    op.drop_index(op.f('ix_board_games_game_id'), table_name='board_games')
    op.drop_index(op.f('ix_board_games_bgg_id'), table_name='board_games')
    op.drop_table('board_games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
