# Available Models Registry
# This file defines all models available in the system.
# Models are organized by provider and only shown in the UI if the corresponding API key is configured.

providers:
  gemini:
    env_var: GEMINI_API_KEY
    models:
      - id: gemini/gemini-2.0-flash-exp
        name: Gemini 2.0 Flash (Experimental)
        supports: [text, image_analysis, structured_output]

      - id: gemini/gemini-1.5-flash
        name: Gemini 1.5 Flash
        supports: [text, image_analysis, structured_output]

      - id: gemini/gemini-1.5-pro
        name: Gemini 1.5 Pro
        supports: [text, image_analysis, structured_output]

      - id: gemini/gemini-2.5-flash-image
        name: Gemini 2.5 Flash Image
        supports: [image_generation]

  openai:
    env_var: OPENAI_API_KEY
    models:
      - id: gpt-4o
        name: GPT-4o
        supports: [text, image_analysis, structured_output]

      - id: gpt-4o-mini
        name: GPT-4o Mini
        supports: [text, image_analysis, structured_output]

      - id: gpt-5
        name: GPT-5
        supports: [text, image_analysis, structured_output]
        temperature_restrictions:
          fixed: 1.0
          note: "GPT-5 only supports temperature=1.0"

      - id: dall-e-3
        name: DALL-E 3
        supports: [image_generation]

  anthropic:
    env_var: ANTHROPIC_API_KEY
    models:
      - id: claude-3-5-sonnet-20241022
        name: Claude 3.5 Sonnet
        supports: [text, image_analysis, structured_output]

      - id: claude-3-opus-20240229
        name: Claude 3 Opus
        supports: [text, structured_output]

  # Future providers (commented out until implemented)
  # openai-video:
  #   env_var: OPENAI_API_KEY  # Requires special access
  #   models:
  #     - id: sora-2
  #       name: Sora 2
  #       supports: [video_generation]
