name: Deploy to Production

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    name: Run Full Test Suite
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: life_os_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov

      - name: Run backend tests (including slow tests)
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/life_os_test
          REDIS_URL: redis://localhost:6379/0
          GEMINI_API_KEY: test_key
          OPENAI_API_KEY: test_key
          REQUIRE_AUTH: false
          JWT_SECRET_KEY: test_secret
        run: |
          # Run ALL tests (including slow) for production
          pytest tests/ --ignore=tests/manual/ -v --tb=short

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --run

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Check bundle size
        working-directory: frontend
        run: |
          BUNDLE_SIZE=$(find dist/assets -name "index-*.js" -exec du -k {} \; | cut -f1)
          echo "Bundle size: ${BUNDLE_SIZE}KB"
          if [ $BUNDLE_SIZE -gt 512 ]; then
            echo "⚠️  Warning: Bundle exceeds 500KB target"
          fi

  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from git tag or commit
        id: version
        run: |
          # Try to get version from git tag
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          IMAGE_TAG="${VERSION}-${COMMIT_SHORT}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Building version: ${IMAGE_TAG}"

      - name: Build images
        run: |
          echo "🏗️  Building Docker images..."
          echo "Version: ${{ steps.version.outputs.image_tag }}"

          # In a real deployment, you would push to a registry here:
          # docker build -t registry.fcy.sh/life-os-api:${{ steps.version.outputs.image_tag }} .
          # docker build -t registry.fcy.sh/life-os-frontend:${{ steps.version.outputs.image_tag }} ./frontend
          # docker push registry.fcy.sh/life-os-api:${{ steps.version.outputs.image_tag }}
          # docker push registry.fcy.sh/life-os-frontend:${{ steps.version.outputs.image_tag }}

          echo "✅ Images built successfully (not pushed - configure registry first)"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, build-images]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://os.fcy.sh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-deployment checks
        run: |
          echo "🔍 Pre-deployment checks..."
          echo "✅ All tests passed"
          echo "✅ Docker images built"
          echo "✅ Manual approval received (via GitHub Environment)"
          echo ""
          echo "📋 Deployment Information:"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Production URL: https://os.fcy.sh"

      - name: Deploy notice
        run: |
          echo "🚀 Deploying to production environment..."
          echo ""
          echo "⚠️  Note: Actual deployment requires server SSH access"
          echo "This workflow validates the code is ready to deploy."
          echo ""
          echo "To deploy manually:"
          echo "1. SSH to production server"
          echo "2. cd /path/to/life-os"
          echo "3. Create backup: ./scripts/backup_postgresql.sh"
          echo "4. git fetch origin"
          echo "5. git checkout main"
          echo "6. git pull origin main"
          echo "7. docker-compose -f docker-compose.production.yml down"
          echo "8. docker-compose -f docker-compose.production.yml up -d --build"
          echo "9. docker exec ai-studio-api alembic upgrade head"
          echo "10. Run smoke tests"
          echo "11. Verify at https://os.fcy.sh"

      # Uncomment and configure when production server is ready
      # - name: Create backup
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.PRODUCTION_HOST }}
      #     username: ${{ secrets.PRODUCTION_USER }}
      #     key: ${{ secrets.PRODUCTION_SSH_KEY }}
      #     script: |
      #       cd /var/www/life-os
      #       ./scripts/backup_postgresql.sh
      #       echo "✅ Backup created"

      # - name: Deploy via SSH
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.PRODUCTION_HOST }}
      #     username: ${{ secrets.PRODUCTION_USER }}
      #     key: ${{ secrets.PRODUCTION_SSH_KEY }}
      #     script: |
      #       cd /var/www/life-os
      #       git fetch origin
      #       git checkout main
      #       git pull origin main
      #       docker-compose -f docker-compose.production.yml down
      #       docker-compose -f docker-compose.production.yml up -d --build
      #       docker exec ai-studio-api alembic upgrade head
      #       echo "✅ Production deployed successfully"

      # - name: Run smoke tests
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.PRODUCTION_HOST }}
      #     username: ${{ secrets.PRODUCTION_USER }}
      #     key: ${{ secrets.PRODUCTION_SSH_KEY }}
      #     script: |
      #       cd /var/www/life-os
      #       ./scripts/smoke_test.sh

      - name: Deployment summary
        run: |
          echo "✅ Production deployment initiated"
          echo "📍 Production URL: https://os.fcy.sh"
          echo "🔍 Monitor logs: docker logs -f ai-studio-api"
          echo "📊 Monitor errors: Check Sentry dashboard (if configured)"

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Deployment status
        run: |
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            echo "✅ Production deployment successful"
          else
            echo "❌ Production deployment failed - ROLLBACK MAY BE NEEDED"
          fi

      # Uncomment to enable Slack notifications
      # - name: Slack Notification
      #   uses: 8398a7/action-slack@v3
      #   if: always()
      #   with:
      #     status: ${{ job.status }}
      #     text: |
      #       Production Deployment ${{ job.status }}
      #       Branch: ${{ github.ref_name }}
      #       Commit: ${{ github.sha }}
      #       Actor: ${{ github.actor }}
      #     webhook_url: ${{ secrets.SLACK_WEBHOOK }}
